In [16]:
import pandas as pd
import requests
import json

import matplotlib.pyplot as plt

In [17]:
df = pd.read_csv('apri_ap_crpouta$defaultview_linear.csv')
print(df.columns)
df.head()

Index(['DATAFLOW', 'LAST UPDATE', 'freq', 'currency', 'prod_veg', 'geo',
       'TIME_PERIOD', 'OBS_VALUE', 'OBS_FLAG', 'CONF_STATUS'],
      dtype='object')

,DATAFLOW,LAST UPDATE,freq,currency,prod_veg,geo,TIME_PERIOD,OBS_VALUE,OBS_FLAG,CONF_STATUS
0,ESTAT:APRI_AP_CRPOUTA$DEFAULTVIEW(1.0),15/05/25 11:00:00,Annual,Euro,Soft wheat - prices per 100 kg,Austria,2015,13.72,NaN,NaN
1,ESTAT:APRI_AP_CRPOUTA$DEFAULTVIEW(1.0),15/05/25 11:00:00,Annual,Euro,Soft wheat - prices per 100 kg,Austria,2016,11.55,NaN,NaN
2,ESTAT:APRI_AP_CRPOUTA$DEFAULTVIEW(1.0),15/05/25 11:00:00,Annual,Euro,Soft wheat - prices per 100 kg,Austria,2017,14.46,NaN,NaN
3,ESTAT:APRI_AP_CRPOUTA$DEFAULTVIEW(1.0),15/05/25 11:00:00,Annual,Euro,Soft wheat - prices per 100 kg,Austria,2018,15.41,NaN,NaN
4,ESTAT:APRI_AP_CRPOUTA$DEFAULTVIEW(1.0),15/05/25 11:00:00,Annual,Euro,Soft wheat - prices per 100 kg,Austria,2019,14.63,NaN,NaN

In [18]:
df = df.drop(['DATAFLOW','LAST UPDATE','freq','OBS_FLAG','CONF_STATUS'],axis=1)
df.head(20)

   currency                        prod_veg      geo  TIME_PERIOD  OBS_VALUE
0      Euro  Soft wheat - prices per 100 kg  Austria         2015      13.72
1      Euro  Soft wheat - prices per 100 kg  Austria         2016      11.55
2      Euro  Soft wheat - prices per 100 kg  Austria         2017      14.46
3      Euro  Soft wheat - prices per 100 kg  Austria         2018      15.41
4      Euro  Soft wheat - prices per 100 kg  Austria         2019      14.63
5      Euro  Soft wheat - prices per 100 kg  Austria         2020      14.88
6      Euro  Soft wheat - prices per 100 kg  Austria         2021      22.65
7      Euro  Soft wheat - prices per 100 kg  Austria         2022      28.05
8      Euro  Soft wheat - prices per 100 kg  Austria         2023      17.90
9      Euro  Soft wheat - prices per 100 kg  Austria         2024      17.60
10     Euro  Soft wheat - prices per 100 kg  Belgium         2015      15.44
11     Euro  Soft wheat - prices per 100 kg  Belgium         2016      13.34
12     Euro  Soft wheat - prices per 100 kg  Belgium         2017      14.14
13     Euro  Soft wheat - prices per 100 kg  Belgium         2018      16.66
14     Euro  Soft wheat - prices per 100 kg  Belgium         2019      15.59
15     Euro  Soft wheat - prices per 100 kg  Belgium         2020      17.45
16     Euro  Soft wheat - prices per 100 kg  Belgium         2021      23.30
17     Euro  Soft wheat - prices per 100 kg  Belgium         2022      32.11
18     Euro  Soft wheat - prices per 100 kg  Belgium         2023      21.05
19     Euro  Soft wheat - prices per 100 kg  Belgium         2024      18.13

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2001 entries, 0 to 2000
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   currency     2001 non-null   object
 1   prod_veg     2001 non-null   object
 2   geo          2001 non-null   object
 3   TIME_PERIOD  2001 non-null   int64
 4   OBS_VALUE    1923 non-null   float64
dtypes: float64(1), int64(1), object(3)
memory usage: 78.3+ KB

In [21]:
df.duplicated().sum()
df.isna().sum()

currency        0
prod_veg        0
geo             0
TIME_PERIOD     0
OBS_VALUE      78
dtype: int64

In [22]:
df[df.isnull().any(axis=1)]

,currency,prod_veg,geo,TIME_PERIOD,OBS_VALUE
154,Euro,Soft wheat - prices per 100 kg,Luxembourg,2021,NaN
155,Euro,Soft wheat - prices per 100 kg,Luxembourg,2022,NaN
156,Euro,Soft wheat - prices per 100 kg,Luxembourg,2023,NaN
157,Euro,Soft wheat - prices per 100 kg,Luxembourg,2024,NaN
253,Euro,Durum wheat - prices per 100 kg,Belgium,2015,NaN
...,...,...,...,...,...
1898,National currency,Feed barley - prices per 100 kg,Ireland,2023,NaN
1916,National currency,Feed barley - prices per 100 kg,Luxembourg,2021,NaN
1917,National currency,Feed barley - prices per 100 kg,Luxembourg,2022,NaN
1918,National currency,Feed barley - prices per 100 kg,Luxembourg,2023,NaN
1919,National currency,Feed barley - prices per 100 kg,Luxembourg,2024,NaN

In [23]:
df[df["OBS_VALUE"].isnull()]["geo"].value_counts()

geo
Luxembourg    40
Ireland       22
Slovenia       8
Belgium        4
Czechia        2
Austria        2
Name: count, dtype: int64

In [28]:
len(df[df["geo"] == "Luxembourg"])
len(df[df["geo"] == "Ireland"])
len(df[df["geo"] == "Belgium"])

64